version: "3"

services:
    drago-pg:
        image: postgres:alpine
        container_name: drago-pg
        restart: always
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=drago
        volumes:
            - ./data/postgresql:/var/lib/postgresql/data
        ports:
            - "5431:5432"