version: '3'

services:

  bounce_server: &bounce_server
    image: drago:latest
    cap_add:
      - NET_ADMIN
    networks:
    - bounce_server
    ports:
      - 8181:8181
      - 8080:8080
    volumes:
    - ./mock.json:/mock.json
    - ./bounce_server.yml:/bounce_server.yml
    container_name: bounce_server

  device_1: &device
    <<: *bounce_server
    ports: []
    volumes:
      - ./device_1.yml:/device_1.yml
    container_name: device_1

  device_2:
    <<: *device
    volumes:
      - ./device_2.yml:/device_2.yml
    container_name: device_2

  device_3:
    <<: *device
    volumes:
      - ./device_3.yml:/device_3.yml
    container_name: device_3

networks:
  bounce_server: