version: '3'

services:

  server: &server
    image: drago:latest
    cap_add:
      - NET_ADMIN
    networks:
    - server
    ports:
      - ${SERVER_UIPORT}:${SERVER_UIPORT}
      - ${SERVER_APIPORT}:${SERVER_APIPORT}
    volumes:
    - ./demo.json:/demo.json
    container_name: server
    environment:
    - SERVER_ENABLED=true
    - SERVER_UI=true
    - SERVER_NETWORK=${SERVER_NETWORK}
    - SERVER_SECRET=${SERVER_SECRET}
    - SERVER_BINDARRUI=:${SERVER_UIPORT}
    - SERVER_BINDARRAPI=:${SERVER_APIPORT}
    - SERVER_MOCKDATA=${SERVER_MOCKDATA}
    - CLIENT_ENABLED=true
    - CLIENT_SERVERADDR=${SERVER_ADDR}
    - CLIENT_DATADIR=${DATADIR}
    - CLIENT_IFACE=${IFACE}
    - CLIENT_SYNCINTERVAL=${SYNC_INTERVAL}
    - CLIENT_JWT=${CLIENT_JWT_SERVER_1}

  client_1: &client
    <<: *server
    ports: []
    volumes: []
    container_name: client_1
    environment:
    - SERVER_ENABLED=false
    - CLIENT_ENABLED=true
    - CLIENT_SERVERADDR=${SERVER_ADDR}
    - CLIENT_DATADIR=${DATADIR}
    - CLIENT_IFACE=${IFACE}
    - CLIENT_SYNCINTERVAL=${SYNC_INTERVAL}
    - CLIENT_JWT=${CLIENT_JWT_CLIENT_1}

  client_2:
    <<: *client
    container_name: client_2
    environment:
    - SERVER_ENABLED=false
    - CLIENT_ENABLED=true
    - CLIENT_SERVERADDR=${SERVER_ADDR}
    - CLIENT_DATADIR=${DATADIR}
    - CLIENT_IFACE=${IFACE}
    - CLIENT_SYNCINTERVAL=${SYNC_INTERVAL}
    - CLIENT_JWT=${CLIENT_JWT_CLIENT_2}

  client_3:
    <<: *client
    container_name: client_3
    environment:
    - SERVER_ENABLED=false
    - CLIENT_ENABLED=true
    - CLIENT_SERVERADDR=${SERVER_ADDR}
    - CLIENT_DATADIR=${DATADIR}
    - CLIENT_IFACE=${IFACE}
    - CLIENT_SYNCINTERVAL=${SYNC_INTERVAL}
    - CLIENT_JWT=${CLIENT_JWT_CLIENT_3}

networks:
  server: